### ISSUE TITLE
发现没有 orderquery 查询订单的接口实现

### ISSUE THREAD

**Issue by tim0991** [medivhzhan/weapp#13]
付款完毕之后 前端的同步回调并不会通知具体的状态，开发者希望调用查询接口来确认状态不是好吗？

**Comment by cnxfire** [comment]
希望增加查询订单接口


###查询订单
应用场景
该接口提供所有微信支付订单的查询，商户可以通过查询订单接口主动查询订单状态，完成下一步的业务逻辑。

需要调用查询接口的情况：

◆ 当商户后台、网络、服务器等出现异常，商户系统最终未接收到支付通知；
◆ 调用支付接口后，返回系统错误或未知交易状态情况；
◆ 调用刷卡支付API，返回USERPAYING的状态；
◆ 调用关单或撤销接口API之前，需确认支付状态；
接口链接
https://api.mch.weixin.qq.com/pay/orderquery

**Comment by medivhzhan** [comment]
已经添加 #17
