### ISSUE TITLE
用beego 架构写的微信支付回调怎么接受不到数据

### ISSUE THREAD

**Issue by ginkgohat** [medivhzhan/weapp#15]
// PayCallback ...
// @Title PayCallback
// @Description 微信支付回调接口
// @router /pay_callback [get]
func (c *WechatPayController) PayCallback() {
	// 必须在下单时指定的 notify_url 的路由处理器下
	err := payment.HandlePaidNotify(c.Ctx.ResponseWriter, c.Ctx.Request, func(ntf payment.PaidNotify) (bool, string) { return true, "" })
	logs.Error("pay_callback error:", err)
...
}

**Comment by ginkgohat** [comment]
已解决

**Comment by Etran-H** [comment]
@ginkgohat 您好，可不可以分享一下“处理支付结果通知”那部分是这么做的？
