### ISSUE TITLE
wrong param with GetParams function

### ISSUE THREAD

**Issue by leezhm** [medivhzhan/weapp#2]
`
// 获取小程序前点调用支付接口所需参数
    params, err := payment.GetParams(res.AppID, res.MchID, res.NonceStr, res.PrePayID, time.Now())
    if err != nil {
        // handle error
        return
    }
`

the paySign should use apikey not MchID, and here is the [wechat app pay document](https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=7_7&index=5)

**Comment by medivhzhan** [comment]
You are right, I've fixed it, thanks for that.
