### ISSUE TITLE
生成小程序码会转义特殊字符

### ISSUE THREAD

**Issue by laeo** [medivhzhan/weapp#26]
刚发现生成的小程序码在开发者工具中打开，URL中的 `&` 字符被转义成  `\u0026` 了，搜了下资料，json 包会默认转义特殊字符。

**Comment by medivhzhan** [comment]
麻烦提供下场景呢，我这边试了下正常的。谢谢：）

**Comment by laeo** [comment]
生成带参数的二维码，比如 `/pages/product/view?id=1&uid=1`  这样，生成出来的二维码用开发者工具打开，链接中的 `&` 就会被转义，然后小程序中测试也是取不到正确的数据，当然，也不会给报错。

**Comment by medivhzhan** [comment]
二维码相关的三个接口都试了下，是正常的呢。

**Comment by laeo** [comment]
又遇到这个毛病，JSON的自动HTML entites编码，导致小程序 scene 参数长度超过32，传入的明明是 `id=9&n=1&uid=1`。然后我尝试把 `postJSONWithBody` 中的 `json.Marshal` 替换成自定义的 encoder，并且 `SetEscapeHTML(false)`，之后再尝试请求腾讯的接口，就能正常生成了，参数一模一样。

另外，不清处腾讯那边是对参数编码做了什么处理，我生成的小程序码的 query 老是很奇怪，小程序开发者工具打开获取到的参数都是未 decode 的，搞得很恼火……搜索也查不到什么资料，太无语了。JSON 编码器的希望能观察下是否你那边也能重现，如果能告诉我更好的解决方案，感激不尽！

:D

**Comment by laeo** [comment]
/pages/index/detail?id=133u0026n=1u0026v=109

微信后台看到的都是这种，不知道哪里出了问题，我之前并未在代码中加入encode逻辑。

**Comment by medivhzhan** [comment]
可以贴下代码不(输入、调用、输出)?否则很难看到问题,因为我这边测试了没问题的;

**Comment by laeo** [comment]
大概如
```
path := "pages/index/detail"
vals := r.URL().Query()
vals.Del("uid")
path = path + "?" + vals.Encode()
h := weapp.QRCode{Path: path}
resp, res, err := h.Get(token)
```
这样子，就很正常的拼接参数到路径后，偏偏就能出问题。参数如 `v=100&n=weapp&id=1` 这样子，通过把 r.URL().Query() 的数据重新编码得到，但是我打印过，也没看到被编码。

**Comment by medivhzhan** [comment]
decodeURI()
decodeURIComponent()
unescape()

JS的这三个函数你试试看;

**Comment by laeo** [comment]
又抽时间测试了下，如果不修改 `postJSONWithBody` 中的 JSON 编码器，生成出来的小程序码用开发者工具扫出来的路径就是错误的。

比如 `pages/index/detail?id=1&uid=1` 用 `weapp.QRCode` 生成出来的小程序码，开发者工具扫描后得到的调试输出是 `根据 sitemap 的规则[0]，当前页面 [pages/index/detail?id=1%255Cu0026uid%3D1] 将被索引` 这样子的。

你都没遇到过这种情况吗？

**Comment by laeo** [comment]
仔细对比了码表，发现出错位置 `%255Cu0026` 这个的来历，`%25` 在URL编码中对应 `%`，替换后得到 `%5Cu0026`，然后 `%5C` 在码表中对应 `\` 转意符，最后得到 `\u0026`，这货是 unicode 编码的 `&` 符号……这套娃套了三层了。

**Comment by laeo** [comment]
禁用转码后，生成的小程序码就正常了。

**Comment by medivhzhan** [comment]
在哪儿禁用的呢?Go程序里面还是微信开发者工具?

**Comment by laeo** [comment]
#36 你看看这个PR，关闭了默认的编码行为，但是不却定是否会对其它接口造成影响，我这边只用了小程序码生成等几个接口，其它接口就无法确认了。

**Comment by medivhzhan** [comment]
请确认下你那边的输入呢,很可能输入的时候就已经被转码了,谢谢 :)

**Comment by laeo** [comment]
我输入的 path 参数是 `fmt.Sprintf` 输出的。

**Comment by medivhzhan** [comment]
谢谢你的帮助 : )

1. 刚才又测试了一下,从输入程序到发送信息到微信服务端都没有进行过自动转义;如果你那边仍然存在这个问题那么可能是这两个原因:
  1. 微信服务器进行了转义;
  2. 输入前已经被转义;

1. `SetEscapeHTML ` 只能转义HTML字符,应该不会转义地址栏的unicode字符;

麻烦你再确认下呢 : )

**Comment by songfei** [comment]
golang 中 json.Marshal 方法会html字符转义， 会把  &  符号转换成 \u0026， 导致微信解析错误， 你可以试下 ， 多个参数 比如  pages/index?a=123&b=456 这种情况， 二维码是正常生成了，但是在小程序里读取参数的时候是错误的。  我看 @laeo  提交的 PR 是正确的， 用 encoder 来代替 Marshal。 

你可以测试下， 也害我调试了一上午。

**Comment by medivhzhan** [comment]
OK, 改了,谢谢两位 : )

**Comment by xizhukarsa** [comment]
确认，go默认行为有问题。
