### ISSUE TITLE
IMGSecCheck 是否可以添加对远程图片的支持

### ISSUE THREAD

**Issue by kenny-yao** [medivhzhan/weapp#32]
您好，因为图片都不在服务器端存储，而是放到专门的图片存储服务器上面，目前IMGSecCheck 方法需要给本地图片的路径，是否能支持远程的图片URL，谢谢

**Comment by medivhzhan** [comment]
[mediaCheckAsync](https://github.com/medivhzhan/weapp#mediacheckasync) 这个接口可以实现 ：）

**Comment by medivhzhan** [comment]
但是还没有线上测试，麻烦你测试下，可行的话还望告知，谢谢 ：）

**Comment by kenny-yao** [comment]
因为我的业务需求的要求同步的，所以，我把这个方法改成了：
func postFormByFile(url, field, imgUrl string, response interface{}) error {
	res, err := http.Get(imgUrl)
	if err != nil {
		return err
	}
	defer res.Body.Close()
	// 获得get请求响应的reader对象
	reader := bufio.NewReaderSize(res.Body, 32 * 1024)
	return postForm(url, field, imgUrl, reader, response)
}

**Comment by medivhzhan** [comment]
已经测试 :)
