### ISSUE TITLE
模版消息推送 缺少测试参数

### ISSUE THREAD

**Issue by zzir** [medivhzhan/weapp#37]
文档地址：https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/subscribe-message/subscribeMessage.send.html

![image](https://user-images.githubusercontent.com/8017428/79967407-5fdb8d00-84c1-11ea-8fbc-f28ffda4b50a.png)

**Comment by medivhzhan** [comment]
谢谢,已经更新到最新版本;
