### ISSUE TITLE
解密时报slice bounds out of range

### ISSUE THREAD

**Issue by conkeyn** [medivhzhan/weapp#5]
I0918 09:11:59.652611 6 AuthUser.go:150] DecryptPhoneNumber params weAppSessionKey: DhdCKRNjmngLstiaaVQR6A== , encryptedPhone: h3NDDnf39Z76MgcWrgNzisq04RXWaF8Yr+3x+dRPbcn1v5akN71LyRlh9CzM2qHlSMEYiuLSNnHfdoZowcQmrJrK1b/15NUaO4u2dS0JBogKhoL3DPc+If+dXRnX8stCbJR6YvR4Md5hu2n/Oycf3nU/VwI5CmXL9um8g+66tUGJzQRhzDD2uHAjlZLpz1r2lZkUcRr56YRfq6/92FLA5w== ,ivPhone: LXxdk1o3Oa0N0+XgZvAUDg==
[31m2018/09/18 09:11:59 [Recovery] 2018/09/18 - 09:11:59 panic recovered:
Host: aws-serverless-go-api.com
09:11:59
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: zh-cn
Content-Type: application/json
Referer: https://servicewechat.com/wx1c44031bd4ac4f81/0/page-frame.html
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Mobile/14F89 MicroMessenger/6.7.2 NetType/WIFI Language/zh_CN
X-Amzn-Trace-Id: Root=1-5ba0c15f-da768fce121aab102b9eb018
X-Forwarded-For: 27.154.25.254
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Golambdaproxy-Apigw-Context: {"accountId":"638953167227","resourceId":"cr4s8x","stage":"qa","requestId":"e5f8cd0a-bb22-11e8-b4bb-4b38a3060d33","identity":{"cognitoIdentityPoolId":"","accountId":"","cognitoIdentityId":"","caller":"","apiKey":"","sourceIp":"27.154.25.254","cognitoAuthenticationType":"","cognitoAuthenticationProvider":"","userArn":"","userAgent":"Mozilla/5.0 (iPhone; CPU iPhone OS
X-Golambdaproxy-Apigw-Stagevars: null
runtime error: slice bounds out of range
/usr/local/go/src/runtime/panic.go:502 (0x42ae08)
/usr/local/go/src/runtime/panic.go:35 (0x429cbd)
/go/src/vendor/github.com/medivhzhan/weapp/util/crypto.go:56 (0x93d510)
/go/src/vendor/github.com/medivhzhan/weapp/util/crypto.go:123 (0x93d510)
/go/src/vendor/github.com/medivhzhan/weapp/weapp.go:118 (0x93dab6)

**Comment by medivhzhan** [comment]
更新版本试试呢，这个Panic的原因可能是你在微信获取到的数据不对引发的。
如果还有问题麻烦跟进下，谢谢🙏。

**Comment by conkeyn** [comment]
好的

**Comment by conkeyn** [comment]
如果数据不正确是不是在base64解码时出现问题了？

**Comment by medivhzhan** [comment]
你看下[代码](https://github.com/medivhzhan/weapp/commit/fae28768ab2ae7d5d3d22a1592ee47fb57212ef6)，是PKCS7反补的时候出的错。
