### ISSUE TITLE
解密用户信息和解密手机号老是报无法解密

### ISSUE THREAD

**Issue by conkeyn** [medivhzhan/weapp#8]

**Comment by medivhzhan** [comment]
请问你校对过数据的有效性吗？

**Comment by caodj** [comment]
我也遇到这个问题，这里面有个坑。如果你先由按钮触发`getPhoneNumber事件`，然后`wx.login`获取`code`，服务器通过`code2Session`获取`session_key`都没问题，但是用这个`session_key`解密数据是乱码的，因为加密数据是微信用上次登陆的密钥加密的

**Comment by medivhzhan** [comment]
@caodj 微信官方文档已经说明了，正常流程应该是先登录再去获取电话号码。
